package crudexample;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.ResultSet;
/**
 *
 * @author DELL
 */
public class EditProduct extends javax.swing.JFrame {
    
    /**
     * Creates new form EditProduct
     */
    public int product_id;
    Connection con;
    public EditProduct() {
        initComponents();
        
       
    }
    
    /**
     * @param  con
     * @param rs
     * 
     */
     public void editProductDetail(ResultSet rs, Connection con){
         try{
             while(rs.next()){
                 this.product_id = rs.getInt("product_id");
                 text_current_category.setText(rs.getString("category"));
                 text_title.setText(rs.getString("title"));
                 text_desc.setText(rs.getString("description"));
                 text_price.setText(rs.getDouble("price")+"");
                 text_quantity.setText(rs.getInt("quantity")+"");
                 
                 
             }
         }
             catch(SQLException e){
                 System.out.println("Error:"+ e.getMessage());
         }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmb_category = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        text_desc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        text_price = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        text_quantity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        text_title = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbl_category = new javax.swing.JLabel();
        text_current_category = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cmb_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stationary", "Sports", "Uniform", "Electronics" }));
        cmb_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_categoryActionPerformed(evt);
            }
        });

        jLabel4.setText("Description");

        text_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_descActionPerformed(evt);
            }
        });

        jLabel5.setText("Price");

        text_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_priceActionPerformed(evt);
            }
        });

        jLabel6.setText("Quantity");

        text_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_quantityActionPerformed(evt);
            }
        });

        jLabel1.setText("DAV |  UPDATE PRODUCT");

        jLabel2.setText("Title");

        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        text_title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_titleActionPerformed(evt);
            }
        });

        jLabel3.setText("Category");

        lbl_category.setText("Current Category:");

        text_current_category.setEditable(false);
        text_current_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_current_categoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbl_category, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_title, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(text_current_category)
                            .addComponent(cmb_category, 0, 266, Short.MAX_VALUE)
                            .addComponent(text_desc)
                            .addComponent(text_price)
                            .addComponent(text_quantity))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_category, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_current_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(text_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(text_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(text_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_categoryActionPerformed

    private void text_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_descActionPerformed

    private void text_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_priceActionPerformed

    private void text_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_quantityActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed

        try{
            String sql = "UPDATE product Set title ='"+text_title.getText()+"',"+
                    "description='"+ text_desc.getText()+"',"+
                    "category='"+cmb_catgeory.getSelectedItem()+"',"
                    +"quantity="+Integer.parseInt(text_quantity.getText())+","
                    +"price="+Double.valueOf(text_price.getText())+"WHERE"
                    +"product_id"+this.product_id;
             
            Statement stmt= this.con.createStatement();
            int status - stmt.executeUpdate(sql);
            if(status>0){
                JOptionPane.showMessageDialog(rootPane,"Product updated");
            }else{
                JOptionPane.showMessageDialog(rootPane,"Something went wrong");
            }
            catch(SQLException e){
                    System.out.println("Error:"+e.getMessage());
                    }
                // TODO add your handling code here:
        // taking input from form

        String title = text_title.getText();
        //taking data from combobox
        String category = cmb_category.getSelectedItem().toString();
        String description = text_desc.getText();

        try{
            //parsig string to integer
            int quantity = Integer.parseInt(text_quantity.getText());

            //Parsing string to double
            double price = Double.parseDouble(text_price.getText());

            // creating sql query and building statement

            String sql ="INSERT INTO product(title,category,description,quantity,price)"
            + "VALUES('"+ title +"', '"+ category +"','"+ description +"',"+ quantity +","+ price +")";

            int status=STMT.executeUpdate(sql);
            if(status>0){
                JOptionPane.showMessageDialog(rootPane,"Product added.");
            }else{
                JOptionPane.showMessageDialog(rootPane,"Something went wrong.");

            }

        }catch(Exception e){// will raise NumberFormatException
            System.out.println("Error: Please enter numeric value only.");
            JOptionPane.showMessageDialog(rootPane,"Please enter numeric value only.");
        }

    }//GEN-LAST:event_btn_updateActionPerformed

    private void text_titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_titleActionPerformed

    private void text_current_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_current_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_current_categoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cmb_category;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_category;
    private javax.swing.JTextField text_current_category;
    private javax.swing.JTextField text_desc;
    private javax.swing.JTextField text_price;
    private javax.swing.JTextField text_quantity;
    private javax.swing.JTextField text_title;
    // End of variables declaration//GEN-END:variables
}
