
package crudexample;
//importing required package
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author DELL
 */
public class ShowProductList extends javax.swing.JFrame {
    
    public final static String DB_NAME="jdbc_crud";
    public final static String DB_USER="root";
     public final static String DB_PASSWORD="*theheirs#123";
     public final static String DB_URL ="jdbc:mysql://localhost:3306/" + DB_NAME;
     public static Connection CON;
     public static Statement STMT;
     public int product_id = 0;

    /**
     * Creates new form ShowProductList
     */
    public ShowProductList() {
        initComponents();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            //creating database connection
            CON= DriverManager.getConnection(DB_URL, DB_USER,DB_PASSWORD);
            STMT = CON.createStatement();
        }
        catch(ClassNotFoundException | SQLException e){
            System.out.println("Error:" +e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_show = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_view = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_product = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DAV | PRODUCT ADD FORM");

        btn_show.setText("Show Products");
        btn_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showActionPerformed(evt);
            }
        });

        btn_add.setText("Add New Product");

        btn_view.setText("View Product");
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });

        btn_edit.setText("Edit Product");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        tbl_product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SNO", "Id", "Title ", "Desc", "Category", "Quantity", "Price"
            }
        ));
        jScrollPane1.setViewportView(tbl_product);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_show)
                        .addGap(35, 35, 35)
                        .addComponent(btn_add)
                        .addGap(18, 18, 18)
                        .addComponent(btn_view)
                        .addGap(29, 29, 29)
                        .addComponent(btn_edit)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_show)
                    .addComponent(btn_add)
                    .addComponent(btn_view)
                    .addComponent(btn_edit))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "SELECT * FROM product";
           
            ResultSet rs = STMT.executeQuery(sql);
            int counter=1; // for serial no
            
            //creating defaulttablemodel object and adding to table
            
            DefaultTableModel model = (DefaultTableModel) tbl_product.getModel();
       
            while(rs.next()){
                int id = rs.getInt("product_id");
                String title = rs.getString("title");
                String category = rs.getString("category");
                String desc = rs.getString("description");
                double price = rs.getDouble("price");
                int quantity = rs.getInt("quantity");
                
                Object data[]={counter,id,title,category,desc,price,quantity};
                model.addRow(data);
                 counter++;
                 
                 
               
            }

                    
                    
        }
        catch(SQLException e){
            System.out.println("Error:" + e.getMessage());
        }
    }//GEN-LAST:event_btn_showActionPerformed

    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
        // TODO add your handling code here:
        int row_no = tbl_product.getSelectedRow();
        
        if(this.product_id<=0 && row_no<0){
            JOptionPane.showMessageDialog(rootPane, "Please select product first");
        }else{
            
            this.product_id= Integer.parseInt(tbl_product.getModel().getValueAt(row_no,1).toString());
            
            String sql = "SELECT * FROM product WHERE product_id=" +this.product_id;
            try{
                STMT = CON.createStatement();
                ResultSet rs = STMT.executeQuery(sql);
                ShowProduct sp = new ShowProduct();
                sp.setVisible(true);
                sp.showProductDetail(rs);
              
            }
            catch(SQLException e){
                System.out.println("Error:" +e.getMessage());
            }
           
           
        }
      
    }//GEN-LAST:event_btn_viewActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        
        int row_no = tbl_product.getSelectedRow();
        if(this.product_id <= 0 && row_no <0){
            JOptionPane.showMessageDialog(rootPane,"please select product first");
        }else{
            this.product_id = Integer.parseInt(tbl_product.getModel().getValueAt(row_no,1).toString());
            String sql = "SELECT * FROM product WHERE product_id=" +this.product_id;
            try{
                STMT = CON.createStatement();
                ResultSet rs = STMT.executeQuery(sql);
                EditProduct ep = new EditProduct();
                ep.setVisible(true);
                
                ep.editProductDetail(rs,CON);//passing ResultSet and Conn
                
            }catch (SQLException e){
                System.out.println("Error:" + e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowProductList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowProductList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowProductList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowProductList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowProductList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_show;
    private javax.swing.JButton btn_view;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_product;
    // End of variables declaration//GEN-END:variables
}
